<?php

/**




































































































































echo "   http://localhost:5173/admin/page-sections\n";echo "🌐 Acesse o painel admin para gerenciar as seções:\n";echo "\n";}    echo "  • {$section['section_name']} ({$section['section_type']})\n";foreach ($defaultSections as $section) {echo "Seções criadas:\n";echo "\n";echo "📂 Arquivo: " . $SECTIONS_FILE . "\n";echo "📊 Total: " . count($defaultSections) . " seções\n";echo "✅ Seções padrão criadas com sucesso!\n";file_put_contents($SECTIONS_FILE, $json);$json = json_encode($defaultSections, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);// Salvar seções}    }        }            exit(0);            echo "❌ Operação cancelada.\n";        if (trim($line) !== 's') {        $line = fgets($handle);        $handle = fopen("php://stdin", "r");        echo "❓ Deseja sobrescrever? (s/n): ";        echo "⚠️  Arquivo de seções já existe com " . count($existing) . " seções.\n";    if (!empty($existing)) {    $existing = json_decode(file_get_contents($SECTIONS_FILE), true);if (file_exists($SECTIONS_FILE)) {// Verificar se já existe}    mkdir($dir, 0755, true);if (!is_dir($dir)) {$dir = dirname($SECTIONS_FILE);// Criar diretório se não existir];    ]        'updated_at' => date('Y-m-d\TH:i:s')        'created_at' => date('Y-m-d\TH:i:s'),        'is_active' => true,        'display_order' => 6,        ],            'show_map' => false            'show_form' => true,            'subtitle' => 'Estamos prontos para atender você',            'title' => 'Entre em Contato',        'content' => [        'section_type' => 'contact',        'section_name' => 'Formulário de Contato',        'section_key' => 'contact_main',        'id' => 6,    [    ],        'updated_at' => date('Y-m-d\TH:i:s')        'created_at' => date('Y-m-d\TH:i:s'),        'is_active' => true,        'display_order' => 5,        ],            'image' => '/about.jpg'            'content' => 'Somos uma empresa especializada em locação de veículos para motoristas de aplicativo.',            'title' => 'Sobre a RV Car Solutions',        'content' => [        'section_type' => 'about',        'section_name' => 'Sobre a Empresa',        'section_key' => 'about_company',        'id' => 5,    [    ],        'updated_at' => date('Y-m-d\TH:i:s')        'created_at' => date('Y-m-d\TH:i:s'),        'is_active' => true,        'display_order' => 4,        'content' => [],        'section_type' => 'investment',        'section_name' => 'Oportunidade de Investimento',        'section_key' => 'investment_info',        'id' => 4,    [    ],        'updated_at' => date('Y-m-d\TH:i:s')        'created_at' => date('Y-m-d\TH:i:s'),        'is_active' => true,        'display_order' => 3,        ],            'show_availability' => true            'show_filters' => true,            'subtitle' => 'Escolha o veículo ideal para você',            'title' => 'Veículos Disponíveis',        'content' => [        'section_type' => 'vehicles',        'section_name' => 'Catálogo de Veículos',        'section_key' => 'vehicles_catalog',        'id' => 3,    [    ],        'updated_at' => date('Y-m-d\TH:i:s')        'created_at' => date('Y-m-d\TH:i:s'),        'is_active' => true,        'display_order' => 2,        'content' => [],        'section_type' => 'services',        'section_name' => 'Serviços Oferecidos',        'section_key' => 'services_main',        'id' => 2,    [    ],        'updated_at' => date('Y-m-d\TH:i:s')        'created_at' => date('Y-m-d\TH:i:s'),        'is_active' => true,        'display_order' => 1,        ],            'cta_link' => '#vehicles'            'cta_text' => 'Ver Veículos',            'background_image' => '/hero-bg.jpg',            'subtitle' => 'Veículos prontos para trabalhar',            'title' => 'Aluguel de Carros para Motoristas de App',        'content' => [        'section_type' => 'hero',        'section_name' => 'Banner Principal (Hero)',        'section_key' => 'hero_main',        'id' => 1,    [$defaultSections = [// Seções padrão do site$SECTIONS_FILE = __DIR__ . '/../data/page-sections.json'; */ * Executar apenas uma vez para popular o banco com as seções iniciais * Script para criar seções padrão no sistema